using System;

namespace Api.Domain.Entities
{
    public class ClientEntity : BaseEntity
    {
        public string DsTipo { get; set; }
        public string DsNome { get; set; }
        public string DsFantasia { get; set; }
        public DateTime? DtCadastro { get; set; }
        public string DsCnpj { get; set; }
        public string DsIes { get; set; }
        public string DsRg { get; set; }
        public string DsCpf { get; set; }
        public DateTime? DtNascimento { get; set; }
        public string DsContato1 { get; set; }
        public string DsSetor1 { get; set; }
        public string DsFone1 { get; set; }
        public string DsContato2 { get; set; }
        public string DsSetor2 { get; set; }
        public string DsFone2 { get; set; }
        public string DsContato3 { get; set; }
        public string DsSetor3 { get; set; }
        public string DsFone3 { get; set; }
        public int? CdClasse { get; set; }
        public int? CdRamo { get; set; }
        public DateTime? DtUltima { get; set; }
        public int? CdVendedor { get; set; }
        public decimal? VlDescper { get; set; }
        public decimal? VlLimite { get; set; }
        public int? CdRota { get; set; }
        public string DsIndicou { get; set; }
        public string DsEndereco1 { get; set; }
        public string DsBairro1 { get; set; }
        public string DsCep1 { get; set; }
        public string DsCidade1 { get; set; }
        public string CdEstado1 { get; set; }
        public string DsEndereco2 { get; set; }
        public string DsBairro2 { get; set; }
        public string DsCep2 { get; set; }
        public string DsCidade2 { get; set; }
        public string CdEstado2 { get; set; }
        public decimal? VlTotal { get; set; }
        public decimal? VlRecebi { get; set; }
        public decimal? VlJuros { get; set; }
        public decimal? VlDescontos { get; set; }
        public DateTime? DtPagou { get; set; }
        public string Obs { get; set; }
        public int? CdPrazo { get; set; }
        public int? CdPortador { get; set; }
        public int? CdCodfis { get; set; }
        public int? Responsavel { get; set; }
        public bool? Net { get; set; }
        public decimal? VlComissao { get; set; }
        public string DsSenha { get; set; }
        public int? CdCond { get; set; }
        public decimal? VlDescper2 { get; set; }
        public int? CdTabpreco { get; set; }
        public decimal? VlDescper18 { get; set; }
        public decimal? VlDescper101 { get; set; }
        public decimal? VlDescper12 { get; set; }
        public decimal? VlDescper102 { get; set; }
        public decimal? VlDescper02 { get; set; }
        public string DsEmail { get; set; }
        public string DsSite { get; set; }
        public int? CdVendedor2 { get; set; }
        public bool? LogPercSt { get; set; }
        public int? TipoCliente { get; set; }
        public string DsCfop { get; set; }
        public string DsNumero1 { get; set; }
        public string DsNumero2 { get; set; }
        public string DsComple1 { get; set; }
        public string DsComple2 { get; set; }
        public int? CdTributa { get; set; }
        public int? CdPisCofins { get; set; }
        public bool? StCliente { get; set; }
        public bool? StFornece { get; set; }
        public int? CdContabil { get; set; }
        public int? CdTpdoc { get; set; }
        public bool? StExportador { get; set; }
        public int? CdPais { get; set; }
        public string DsMsgFiscal { get; set; }
        public int? VlMediaDiasPg { get; set; }
        public string DsCnae { get; set; }
        public DateTime? DtAtual { get; set; }
        public int? CdCrt { get; set; }
        public string DsObsFat { get; set; }
        public int? CdTabprecoFrete { get; set; }
        public string DsIm { get; set; }
        public string DsSuframa { get; set; }
        public int? CdTipoFrete { get; set; }
        public int? CdOperacao { get; set; }
        public DateTime? DtConsultaCredito { get; set; }
        public decimal? VlDescmax { get; set; }
        public int? CdUsuario { get; set; }
        public string DsLogo { get; set; }
        public int? CdVersao { get; set; }
        public bool? StAssinatura { get; set; }
        public bool? StFeedback { get; set; }
        public int? TipoEmpresa { get; set; }
    }
}
